---
version: 0.2
phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
  pre_build:
      commands:
        - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
        - REPO="985266629220.dkr.ecr.eu-west-1.amazonaws.com/aws-demo"
        - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build --build-arg COLOR=blue --build-arg ERROR_RATE= --build-arg LATENCY= -t $REPO:$TAG .

  post_build:
    commands:
      - docker push $REPO:$TAG