---
version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    commands:
      - ls
      - ls $CODEBUILD_SRC_DIR_deployCode
      - env
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
  pre_build:
      commands:
        - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
        - REPO="985266629220.dkr.ecr.eu-west-1.amazonaws.com/aws-demo"
        - $(aws ecr get-login --no-include-email)
  build:
    commands:
      # - docker build --build-arg COLOR=orange --build-arg ERROR_RATE=0 --build-arg LATENCY=0 -t $REPO:$TAG .

  post_build:
    commands:
      # - docker push $REPO:$TAG
      - cd $CODEBUILD_SRC_DIR_deployCode
      - ls
      - sed -i '' "s#image:\ $REPO:.*#image:\ $REPO:$TAG#g" ./canary/canary-rollout.yaml
      - git commit -am "version update to $REPO:$TAG"
      - git push origin test